### ISSUE TITLE
Make improvements easier and less error-prone by expanding the test suite and cleaning up the codebase.

### ISSUE THREAD

**Issue by jamestmartin** [LastArtistStanding/last-artist-standing#92]
The primary goal is, of course, DAD 2.0 stuff: a lot of extra features, a redesign, and sweeping changes. However, I think there's some other stuff that ought to be done first which could make writing all that substantially easier. At least I personally find myself constantly worried about breaking things! But I think this situation could be improved upon if we took a bit of time aside to alleviate some technical debt.

And don't get me wrong: the current codebase is *good enough*. It's not *broken*, and it doesn't need a rewrite. As far as maintaining a working website goes, it's just fine as-is. I just think that if there are going to be massive changes, the effort of doing some cleanup would be worth it.

My current concerns with the codebase:

1. Making changes is scary.
   * It's easy to break stuff, and Ruby's extreme dynamism gives you no guard rails.
   * Manually testing the code is tedious and error-prone. I've already managed to let multiple bugs slip by, and even after manual testing and code review, I still don't feel like I can trust my code.
2. The code feels fragile. A lot of error handling and checks just aren't there. Edge cases are ignored and allowed to crash. Among other things:
   * Incorrect parameters will often crash the controller.
   * Authorization checks often only exist in the view, or not at all.
   * The password reset bug...
3. The code could use some clean-up.
   * A lot of code doesn't follow Ruby or Rails idiom or style (just ask the linter! and e.g. not using associations)
   * A lot of code is repetitive and could afford to be abstracted out broken up into smaller functions
   * A lot of code is just kinda iffy in general or could just plain be done better (link_form!!)

I think the best way to solve the above problems would be through expanding the test suite:

1. Automated testing means you don't have to do those tests yourself! The automated tests won't forget to test something, or accidentally test it wrong.
   It's also a lot faster and easier than doing it yourself. You can safely make your changes, and if the tests still pass, you can have a lot more confidence that your code still works.
2. Automated testing encourages thinking about *every* case, including edge cases. In the process of writing tests, we're likely to catch a lot of the subtle bugs or fragile code and be able to fix it.
   Furthermore, it means we don't have to *remember* all of those edge cases when we go to test our changes.
3. Once the automated tests are there, refactoring and cleaning up code will be a lot easier, because again, the automated tests will check that we didn't break anything for us, saving a lot of time and 

Here's an overview of how I'd go about making the above improvements:

1. Improve the test suite:
   - [ ] Figure out how to mock ImageUploaders so we can test submissions and badges.
   - [ ] Set up a bunch of fixtures to write tests against.
   - [ ] Removing the dependency on the `dad_tasks` being run in the test environment (and depending on fixtures instead).
   - [ ] Write tests for both new and *existing* code that ensures, among many other things:
     - [ ] That nothing is going to cause the controller or view to crash!
     - [ ] The (semantically) correct HTTP status code is returned
     - [ ] The correct template is rendered
     - [ ] That authorization is verified both on the front-end and back-end
     - [ ] That database updates work correctly, e.g. when a challenge is deleted:
       - all participations, notifications, badges, etc. are deleted
       - nothing that *isn't* associated with that challenge is deleted
     - [ ] That simultaneous actions are handled correctly, e.g. a new user can't upload 15 submissions at once
   - [ ] Also, set up a code quality and test coverage tracker would be fun/helpful so we can view our progress
2. Clean up the code:
   * [ ] (#89) Make all code pass the linter, with a combination of automatic and manual fixes.
   * [ ] Refactor code according to complexity metrics.
   * [ ] Just improve code quality in general. There's a lot of stuff that could use cleaning up or rewriting. This includes what you were alluding to in response to #83. 
   * [ ] (#80) Support the file-based carrierwave backend so S3 isn't necessary for the development environment. This will make contributing easier.
     * This may actually necessary to be able to test submissions anyway.
   * [ ] Rework the data model: some code is unnecessarily entangled.
   * [ ] Make existing features better before moving onto new ones, e.g. the comments and notifications system.

**Comment by jamestmartin** [comment]
This issue is related to the rubocop task:

These issues (so, so, so many issues) are part of the "improve the test suite" task of this issue: #171 #172 #173 #174 #175 #176 #177 #178 #179 #180 #181 #182 #183 #184 #185 #186 #187 #188 #189 #190 #191 #192 #193 #194 #195 #196 #197 #198 #199 #200 #201 #202 #203 #204 #205 #206 #207 #208 #209 #210 #211 #212 #213 #214 #215 #216 #217 #218 #219 #220 #221 #222 #223 #224 #225 #226 #227 #228 #229 #230 #231 #232 #233 #234 #235 #236 #237 #238 #239 #240 #241 #242 #243

The code cleanup sub-tasks have been organized into stages by @the1banana:
> Stage 1: Quick hotfixes to fix most pertinent bugs with the site, important QoL stuff. I will list these out as soon as I can, just gotta get it all straight.
> Stage 2: Work on getting test suites up to snuff. Get test coverage up to 70% coverage, and functional "raw-logic" methods need 100% coverage.
> Stage 3: Set policies for code-base best practice, configure rubocop accordingly. [...] Refactor code in compliance for better maintainability.
